### ISSUE TITLE
latest insomnia version broke this plugin - editor no longer shows in UI

### ISSUE THREAD

**Issue by ortonomy** [syl20lego/insomnia-plugin-aws-cognito-token#14]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/6688676/211472051-e90862d2-7975-489f-b6a3-d3518f8bc678.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6688676/211472109-809aef41-a3fa-400a-91fa-ba346ff9e4c4.png">

**Comment by syl20lego** [comment]
looks like the plugin is not installed. You can re-open it if you have more information.
