### ISSUE TITLE
Unable to save because of parse error

### ISSUE THREAD

**Issue by kossmoboleat** [syl20lego/insomnia-plugin-aws-cognito-token#2]
When I enter the fields as needed the plugin successfully creates a token, but then when I close the dialog Insomnia still complains about the syntax of the expression and it's not saved then. The issue seems similar to this one: https://github.com/getinsomnia/insomnia/issues/1388

![Screen Shot 2019-03-22 at 08 50 24](https://user-images.githubusercontent.com/1618518/54808741-66298500-4c81-11e9-8cc9-1fbab99d7122.png)

I've also tried to enter the expression directly in Nunjucks power user mode, but there's still an error.

**Comment by syl20lego** [comment]
Thanks for raising this issue, I updated the screen shoot. The variable need to be enclose in double quotes `"`. 

Sorry about that, hope this works for you.

**Comment by kossmoboleat** [comment]
Nice! Thanks, that works. This is a nice tool and it's cool that you replied so quickly.

There's a slight inconsistency in the screenshots now because the environment variable should be called COGNITO_TOKEN instead of COGNIATOA_TOKEN.

**Comment by syl20lego** [comment]
thanks, it's a pleasure to help,  sorry for the typo, it is fixed now
