### ISSUE TITLE
Error installing into Insomnia 6.6.2

### ISSUE THREAD

**Issue by JohnAtFenestra** [syl20lego/insomnia-plugin-aws-cognito-token#4]
Attempted to install insomnia-plugin-aws-cognito-token version 0.11 into Insomnia 6.6.2. When installing from Plugins, I receive the following error:

Yarn error {"type":"warning","data":"package.json: No license field"}

No other information is available and the Plugin doesn't turn up in the list of installed.

**Comment by JohnAtFenestra** [comment]
As an update, I was able to install by using GIT Clone into the Plugins directory as accessed via Preferences/Plugins.

**Comment by syl20lego** [comment]
sorry about that...yes only work around for now is to go to the plugin folder and manually install the plugin:
git clone https://github.com/syl20lego/insomnia-plugin-aws-cognito-token.git
cd insomnia-plugin-aws-cognito-token                        
npm install

**Comment by hockeymikey** [comment]
I'm still dealing with this. Anyone know why it's doing this?
